(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> mFilename"
p3
sS'layer'
p4
S'/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/product.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n\n\n\ndef index():\n\n    return dict(mRows=db(db.tbProducts.id>0).select())\n\n\n\n@auth.requires_login()\ndef add():\n    Validator.admin()\n\n    mForm=SQLFORM(db.tbProducts, submit_button=T(\'Save and add an image\'))\n\n    Validator.form_process(mForm, URL(\'product\', \'index\'))\n\n    return dict(mForm=mForm)\n\n\n\n@auth.requires_login()\ndef edit():\n    Validator.admin()\n    Validator.valide_args(1)\n\n    db.tbProducts.id.readable = False\n\n    mForm=SQLFORM(db.tbProducts,\n            db.tbProducts(request.args[0]),\n            submit_button=T(\'Save changes\'))\n\n    Validator.form_process(mForm, URL(\'product\', \'index\'))\n\n    return dict(mForm=mForm, mFormImage=get_image_add_form(request.args[0]))\n\n\n\n\n@auth.requires_login()\ndef get_image_add_form(mProductId):\n  Validator.admin()\n\n  mForm = FORM(LABEL(T("File")+"(s):"), INPUT(_name=\'mFiles\', _type=\'file\', _multiple=\'\'),\n      BR(),INPUT(_type=\'submit\', _value=T("Send images")))\n\n  if mForm.accepts(request.vars, formname="mForm"):\n    print \'here1\'\n    if hasattr(request.vars, \'mFiles\'):\n      print \'here2\'\n      if len(request.vars.mFiles) > 0:\n        print \'here2\'\n\n        mFiles = request.vars[\'mFiles\']\n        if not isinstance(mFiles, list):\n          mFiles = [files]\n\n        print \'#=================\', request.now\n        for f in mFiles:\n          print f.mFilename\n          mFile = db.tbProductsUploads.mFile.store(f, f.mFilename)\n          db.tbProductsUploads.insert(mFile=mFile, mFilename=f.mFilename, mProduct=mProductId)\n          db.commit()\n\n        #redirect(URL(\'product\', \'index\'))\n      else:\n        print \'here error\'    \n        mForm.errors.mFiles = "No files selected"\n\n  return mForm\n\nresponse._vars=response._caller(edit)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/product.py", line 74, in <module>\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/gluon/tools.py", line 4236, in f\n    return action(*a, **b)\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/product.py", line 37, in edit\n    return dict(mForm=mForm, mFormImage=get_image_add_form(request.args[0]))\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/gluon/tools.py", line 4236, in f\n    return action(*a, **b)\n  File "/Users/fabiofilho/Documents/Deployment/Web2Py/web2py/applications/perimoveis/controllers/product.py", line 62, in get_image_add_form\n    print f.mFilename\n  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cgi.py", line 521, in __getattr__\n    raise AttributeError, name\nAttributeError: mFilename\n'
p11
s.